### ISSUE TITLE
Does not work for graphs with negative values

### ISSUE THREAD

**Issue by michaelgriffithus** [jedtrow/Chart.js-Rounded-Bar-Charts#1]
![screenshot 2017-06-15 15 26 42](https://user-images.githubusercontent.com/12091730/27198171-157b6504-51df-11e7-969b-9c295a81830b.png)

**Comment by jedtrow** [comment]
Finally found time to fix this issue in commit [e3e7702](https://github.com/jedtrow/Chart.js-Rounded-Bar-Charts/commit/e0d811e27559d0535155069b2b13139ad672ad1e)
